### ISSUE TITLE
Capacity emote slots

### ISSUE THREAD

**Issue by kralrepreskrontkisori** [SevenTV/Extension#1002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Chrome

### Current Behavior

Will it still take that long for a capacity of 1000 emotes per slot? My account has a limit of 600, many other people's has a limit of 1000. Doesn't make sense, do you have to be subscribed, pay or something?

### Expected Behavior

Will it still take that long for a capacity of 1000 emotes per slot? My account has a limit of 600, many other people's has a limit of 1000. Doesn't make sense, do you have to be subscribed, pay or something?

### Steps To Reproduce

Will it still take that long for a capacity of 1000 emotes per slot? My account has a limit of 600, many other people's has a limit of 1000. Doesn't make sense, do you have to be subscribed, pay or something?

**Comment by MatinAniss** [comment]
This is not a bug, newer users can only have up to 600 emote slots.
