### ISSUE TITLE
[BUG] Youtube features not working

### ISSUE THREAD

**Issue by MiguelMachado-dev** [SevenTV/Extension#1005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Firefox

### Current Behavior

Can't see 7TV icon on chat
Emotes does not work
no features works on youtube

### Expected Behavior

See 7TV icon near chat
True theater mode
See emotes on chat

### Steps To Reproduce

- Extension version 3.0.10.1000
- Firefox version 123.0

![image](https://github.com/SevenTV/Extension/assets/29252011/686f28d8-7829-4355-b107-9da176f1bbf2)

**Comment by lennartkloock** [comment]
We are currently in the process of rewriting the extension from scratch here https://github.com/SevenTV/SevenTV. It will work on Youtube.
