### ISSUE TITLE
[BUG] extension settings disappear

### ISSUE THREAD

**Issue by F1R4NV4R** [SevenTV/Extension#1044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### Current Behavior

In the new version of the extension(3.1.0.1000 nightly), when opening the 7tv popup on Twitch, when going to any tab, the nickname is displayed and that’s it. Closing a popup and opening it doesn't always help
![image](https://github.com/SevenTV/Extension/assets/138937804/31e21331-58ca-460f-a785-b6d4c463cfc2)

### Expected Behavior

settings in the popup are displayed as expected
![image](https://github.com/SevenTV/Extension/assets/138937804/607c9d60-1317-4e20-b148-309d9ed7d0af)

### Steps To Reproduce

open a page with an active broadcast 
open 7tv popup
open any settings in the popup

**Comment by Excellify** [comment]
Should be resolved by 454848e
