### ISSUE TITLE
Gif emotes animation reset after its posted again[Bug] 

### ISSUE THREAD

**Issue by Cofic** [SevenTV/Extension#171]
**Describe the bug**
Gif emote animation is reset after the same one is posted in chat. Which means if people keep posting it, it keeps reseting and not progressing at all. Which breaks the point of a gif. 

The issue is solely with 7tv, because i tried disabling it, and both ffz and bttv worked fine then. I also noticed that when you zoom in the tab with (ctrl +) theres no problem anymore with the animation reset. 

**To Reproduce**
1. Open a stream which has an active chat, where there will be multiple people posting the same gif in quick succession.
2. See the problem listed above.

**Expected behavior**
Gif emotes should do a full animation even after the same one is posted in chat.

**Version:**
I am using firefox(latest 93.0) and win10(latest). 
The version where the bug is occuring 2.0.0

**Comment by jkrakowiak** [comment]
https://github.com/FrankerFaceZ/FrankerFaceZ/issues/985 Has to do how firefox displays animated images, unsure how BTTV does not have this, only 7tv.

**Comment by AnatoleAM** [comment]
Seems like a Firefox issue, as there's also nothing fancy the 7TV extension does to display images. It is, also, just a standard `<img>` tag.

I'm sure it would be trivial for Mozilla to fix something like this, however from what I've seen Firefox isn't a very active project and I see bug reports stand there for years without any response, so I wouldn't hold my breath. Would just advise to use a more up to date web browser if possible

**Comment by jaondayko** [comment]
I think a counter-point to that though is similar to the FrankerFaceZ note on it, BTV has no issue with this

**Comment by jaondayko** [comment]
I'll look further into it to see if I can find a way to reproduce it accurately, so far it has been just look at any channel with a lot of people chatting/using gif emotes and it happens

**Comment by csrapr** [comment]
As the creator of the original issue on ffz, I'm looking forward to what you guys find. I refuse to use a chromium browser :)

**Comment by csrapr** [comment]
I'm looking forward to what you guys find. I refuse to use a chromium browser :)
I've been looking for a fix for a while now (ever since I opened the issuue on FFZ) and the only thing I could find was that zooming in fixed the problem, but then the rest of chat looks too big.

**Comment by jakethewake** [comment]
This happens in erobb's chat a lot, especially with the "LMAOOOOOOOOOO" emote (https://7tv.app/emotes/61e89f42699aab943eab83c3).

**Comment by jaondayko** [comment]
Yeah, I was looking into this, it appears that using `srcset` instead of `src` for loading a gif/image/whatever will cause it to appear correctly w/o reloading the image. If you set it to just src, it will cause it to "restart" the image every time it is added into the page

**Comment by jaondayko** [comment]
Using the latest beta version of 7TV on Firefox (v3 beta) seems to have fixed the issue.
