### ISSUE TITLE
[Request] Youtube: Keybind for Theater Mode 'T' Should Toggle 7TV True Theater Mode

### ISSUE THREAD

**Issue by robmonte** [SevenTV/Extension#174]
The default keybind to toggle Theater Mode, 'T', still toggles the youtube version. Instead, the keybind should be intercepted to toggle 7TV's version of True Theater Mode instead. 

**Version:**
2.0.1

**Comment by Excellify** [comment]
I would say that depends on preference. At the moment they're implemented as separate modes so replacing the keybind does not follow that notion. A setting that would allow you to replace the keybind could be a good solution tho.

**Comment by robmonte** [comment]
I agree that a toggle would be ideal for those that don't want this. However, I am of the opinion that it should default to overriding the keybind. Youtube's built-in theater mode pushes the chat below the stream video, off screen. Combine that with the likely fact that most users of 7TV are coming from Twitch, they (probably) want the 7TV True Theater mode feature over the default one because it matches Twitch's style of theater mode.

**Comment by robmonte** [comment]
So I've been using this extension: https://addons.mozilla.org/en-US/firefox/addon/youtubelivestreamstheatermode/
And I think it has a great feature to consider also implementing as part of 7TV. On that extension, you can mouse over a small section of the video player at the top to show all of the video info Youtube usually puts under the video (title, viewer count, description, like/dislike/share, etc). It is very bad UX to have to alternate theater mode on and off to be able to see this info. This would also match Twitch's theater mode behavior, similar to my point above regarding the T button remap as well. Of course, a user-toggle is always a welcome way to control this.
