### ISSUE TITLE
The logo 7tv uses for settings and emote menu's is blurry.

### ISSUE THREAD

**Issue by treuks** [SevenTV/Extension#197]
**Describe the bug**
The logo 7tv uses for settings, and the emote picker, is blurry, due to it being scaled down from a **512x512** **webp** image

**To Reproduce**
1. Go to a twitch page, or a youtube live stream
2. Look at the 7tv logo
3. See that it is blurry

**Expected behavior**
It should be a nice and not blurry 7tv logo

**Screenshots**
![image](https://user-images.githubusercontent.com/18615981/148410647-2d937db8-6a99-4840-b186-b63c0140dde6.png)

![image](https://user-images.githubusercontent.com/18615981/148410695-a6f40188-bdfb-4328-b3cc-4653426767d6.png)

![image](https://user-images.githubusercontent.com/18615981/148410741-9d02fd79-b1fa-4980-824e-839cd15b4b04.png)

**Version:**
Chromium 94.0.4606.61
SevenTV 2.0.2

**Comment by NS2555** [comment]
As a solution, i have created a nice and pixel aligned svg version of the logo 

```
<svg width="16" height="16" viewBox="0 0 4.233 4.233" xmlns="http://www.w3.org/2000/svg"><path style="fill:#0e0e10;fill-opacity:1;stroke:none;stroke-width:.264583px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1" d="m21.431 7.408-1.058 1.059-1.323-1.323V8.73l-.53-.529V6.35l1.588-1.058-2.645.264-.265-.529 4.233-.53v.53l-2.116 1.588 1.058 1.058 1.058-1.058z" transform="translate(-17.198 -4.498)"/></svg>
```
You are free to use it everywhere for the extension

**Comment by Excellify** [comment]
It dosn't appear blurry to me?

**Comment by NS2555** [comment]
look at how sharp the edges are on the native website buttons compared to the 7tv button

**Comment by Excellify** [comment]
Hmm, I can maybe see some blur on the images you linked. I dont have the same blur when its rendered for me tho. :thinking: 
What resolution is this?

**Comment by NS2555** [comment]
1920x1080p chromium on linux

**Comment by NS2555** [comment]
hmm, it seems like it looks better in firefox 
![image](https://user-images.githubusercontent.com/18615981/148424650-b9086c77-403a-4a30-892e-3ec120267c06.png) (firefox)

![image](https://user-images.githubusercontent.com/18615981/148424717-d48ac8d9-ac8b-4dca-8925-84b261a65cec.png) (chromium)

**Comment by Cryptizism** [comment]
The logo appears to be "blurry" due to how chrome downscales its images.
If you wanted to fix this *(Would've made a PR but I messed up stuff with my fork and can't rn)* you can add: `image-rendering: -webkit-optimize-contrast;` to the CSS of the logo.

Without `image-rendering: -webkit-optimize-contrast;`
![image](https://user-images.githubusercontent.com/60571306/154872454-71374d60-9650-494c-96f7-9ad658c9d9b9.png)
With `image-rendering: -webkit-optimize-contrast;`
![image](https://user-images.githubusercontent.com/60571306/154872495-5db7aeb7-f789-49bc-953d-f93d27ee41fb.png)

The edges appear less blurry and more defined

You could also just input an image the same size as it will be displayed so that there is no unwanted appearances with the downscaling

**Comment by treuks** [comment]
i will attempt to pr this i guess

**Comment by Cryptizism** [comment]
> EDIT 2: APPARENTLY adding it manually makes it look smoother and more clear, but if it gets added by the extension itself it looks like the images above

I can't seem to replicate the error when it's added through the extension, make sure the syntax is correct.
Works fine for me on **Version 98.0.4758.102 (Official Build) (64-bit) Google Chrome**

**Comment by treuks** [comment]
Version 98.0.4758.102 (Official Build, ungoogled-chromium) (64-bit) the syntax is correct

**Comment by Cryptizism** [comment]
I don't know why adding styles from an extension would behave any differently to it being edited in dev tools

**Comment by Cryptizism** [comment]
So what are the plans for this issue, you just gonna close it? @AnatoleAM

**Comment by treuks** [comment]
one second, i'll see if it's fixed for me and then close it myself

**Comment by Cryptizism** [comment]
> one second, i'll see if it's fixed for me and then close it myself

Anatole said that the css wasn't really worth it, don't know if he wanted to implement an svg or just skim over this issue

**Comment by treuks** [comment]
why not?

**Comment by treuks** [comment]
i see, in case anatoleam actually needs a proper vector version of the logo i can create it, had much more experience with that now so it won't be as bad as the one i linked prior in the issue

**Comment by Excellify** [comment]
I a lot of the weird rendering is caused due to using the image as a mask instead of a scaled image. This was so that the colour could be changed without having different assets. A proper vector version would be optimal yea.

**Comment by treuks** [comment]
not sure if this would be the best way to share it but i have created an svg version of the logo
https://drive.google.com/file/d/1atRBCwyv8VfgARVpTJXh3GLfp5fStMDY/view?usp=sharing 

i think it looks good scaled down too

![7tv_logo_optimized](https://user-images.githubusercontent.com/18615981/167141608-b90d9c20-7ae0-4693-9de2-be776b40eff3.png)

just obviously need to recolor it, but it's an svg, extremely easy to do so

**Comment by treuks** [comment]
apparently the logo on the main page is already svg and i spent all this effort trying to recreate it, OMEGALULiguess
