### ISSUE TITLE
[Feature request] Handle FFZ User-Specific Global Emotes 

### ISSUE THREAD

**Issue by RealityRipple** [SevenTV/Extension#212]
The 7TV App shows the "OBOY", "OiMinna", and "AndKnuckles" emotes in the emote menu, which are user-specific global emotes in the "Sten's Cheaty Emotes" list, only usable by sirstendec.

The correct action is to parse the `default_sets` array and add sets with an ID matching that array (currently only set number 3) to the allow list, then go through the `users` associative array and allow access to the set marked by the keys in that array only if the user's name is listed in that key's value array (currently only set number 4330 is listed, with only "sirstendec" in the value array). If the current user is not in the `users` array for a set, that set should not show up in the menu.

The purpose is to let certain users have access to a set of personal emotes in all channels, without asking for the user name with each `/set/global` call.

For direct-source details, see the `/set/global` section of https://www.frankerfacez.com/developers.

Tested on v2.1.4

**Comment by AnatoleAM** [comment]
Uh, was not aware of that, and it seems we are not the only ones implementing FFZ's globals "wrong" as popular chat client Chatterino also has these as global. 

Though that seems to be correct information, this would be a very low priority fix. Unless someone wants to implement this behavior we probably won't do it, as it's simply not worth spending any development time for something that affect a single person.
