### ISSUE TITLE
Safari extension

### ISSUE THREAD

**Issue by jobukkit** [SevenTV/Extension#219]
Please port the extension to Safari for Mac OS.

**Comment by Cameron2920** [comment]
I'm not sure if its worth it because Safari extensions require a $100/year apple developer account and it makes up only 4% of the market share. I'm available to help if this something 7TV wants to do.

**Comment by AnatoleAM** [comment]
Are Mac users not able to download a web browser other than the built-in one?

**Comment by Cameron2920** [comment]
> Are Mac users not able to download a web browser other than the built-in one?

Chrome and Firefox are available on Mac.

**Comment by AnatoleAM** [comment]
Right, then why not just do that? What advantages does Safari have over existing alternatives? It's sort of like installing Windows then keeping Explorer as your main browser, doesn't make sense to me. Just get a better browser
![image](https://user-images.githubusercontent.com/9599344/155008108-1614a60b-e048-4f78-a767-ba7d7338cfac.png)

**Comment by jobukkit** [comment]
> What advantages does Safari have over existing alternatives? It's sort of like installing Windows then keeping Explorer as your main browser, doesn't make sense to me. Just get a better browser

I use Firefox when my MacBook is plugged in, and Safari when it's not. Safari is more battery-efficient and better integrated with the OS.
Internet Explorer was purposefully standards-incompliant, it's not comparable to Safari.

**Comment by Excellify** [comment]
Seems like the extension would need patches to work on safari. Just converting it using xcode and running it unsigned completely breaks the chat. I have no experience with safari extension so I dont know how much work would be needed to fix it.

**Comment by treuks** [comment]
@BlazingFire007 i'm not a mac os user, but i've heard people enjoy [the orion browser](https://browser.kagi.com/), it's like a better version of safari for mac os with extensions. you should try it and see if it works for you
#ad #sponsored #xddddddddddddddddddddddddddddddddddddddddddddddddd
