### ISSUE TITLE
[Bug] 7TV emote menu and emotes don't show up at a linked youtube channel

### ISSUE THREAD

**Issue by NEET-FEET** [SevenTV/Extension#253]
The 7TV emote menu and emotes don't show up on a particular youtube channel, the youtube is linked to https://7tv.app/users/6259e66985873c051292d6f9 and the youtube channel is https://www.youtube.com/channel/UCl63ZOm_bepvwoKjw24rogA, not sure what is the cause, some things to note is that the chat is in subscribers only mode. 
![image](https://user-images.githubusercontent.com/38628821/164382434-d8759351-d53f-4f40-8863-a00ff43b9794.png)

Not sure how to reproduce other than wait till the channel is live and check it out yourself. I don't own the channel, I'm a moderator in contact with the streamer, each time I checked it didn't show (multiple streams). 

Checked on two PCs one windows other linux, both using firefox browser with version 2.2.1 of 7tv. Also asked in the discord, where I got confirmation that it wasn't just me experiencing the undesired behavior.

**Comment by robmonte** [comment]
Check to see if maybe this is your issue: https://github.com/SevenTV/SevenTV/issues/261

Currently hiding the emote menu button on twitch will also hide it from youtube
