### ISSUE TITLE
[Bug] After being banned or timed-out, 7TV emote icon disappears in Firefox

### ISSUE THREAD

**Issue by Bilge** [SevenTV/Extension#254]
**Describe the bug**
After being banned or timed-out, the 7TV emote icon, below the chat bar, disappears from Firefox/Windows and is never restored until the page is refreshed. Moreover, emote tab-completion stops working for all emotes, including Twitch native.

**To Reproduce**
1. Get timed out
2. Observe icon disappears

**Expected behavior**
Being timed out should not remove the emote menu or disable emote completion when the timeout expires.

**Screenshots**
| Before | After |
|-|-|
| ![image](https://user-images.githubusercontent.com/470626/165132700-e3f04b84-d4a3-4c68-899a-fc56be0a13d6.png) | ![image](https://user-images.githubusercontent.com/470626/165132622-e0fc4a40-c681-44b2-aea9-e588bc9cefdd.png) 

**Version:**
2.2.1

**Comment by asger-finding** [comment]
![image](https://user-images.githubusercontent.com/49583904/170866363-e9e5e391-b9b0-453c-a7a4-69d918b6628f.png)

![image](https://user-images.githubusercontent.com/49583904/170866419-d83cba85-df55-423d-9840-f825673a7854.png)

![image](https://user-images.githubusercontent.com/49583904/170866894-faeb08e0-d9ce-46ee-9aeb-33e3b79ce5ff.png)

Can replicate in Librewolf (Hardened Firefox fork) with 7TV version 2.2.2.

**Comment by AnatoleAM** [comment]
Fixed in v3.0.0 (aaaac7f)
