### ISSUE TITLE
[Bug] Tab completion for nicknames not working

### ISSUE THREAD

**Issue by ValeINTina** [SevenTV/Extension#256]
After installing 7tv as soon as an emote and a nickname start with the same letters I can't tab to complete with the nickname. 
For example, if someone in chat is called Kevin, I write K, tab and fill with KAPOW, KEKW, then KAPOW and KEKW again and again, without finding the nickname in the completion tab.

I disactivated 7tv and this issue got solved.

I even tried to swap between prioritizing emotes or nicks in the settings but nothing changed.

**Comment by Cryptizism** [comment]
do you have this enabled in 7tv settings?
![image](https://user-images.githubusercontent.com/60571306/166533693-767232ad-ffe7-4bf1-b356-dc788a0252fe.png)
