### ISSUE TITLE
[Bug] Default Twitch emotes don't auto-complete

### ISSUE THREAD

**Issue by ahtee** [SevenTV/Extension#257]
**Describe the bug**
using 7tv extension alone does not Tab auto-complete the default available twitch emotes (The emotes provided without any extension, example: 4Head, BatChest)

**To Reproduce**
1. with only 7tv installed on a browser (Im using FireFox), Go to a Twitch.tv channel, it can be your own account
2. Click on the Input box in chat and try Auto-completing a default Twitch emote (try: 4Head, BatChest, Shush, TwitchUnity)
3. See that the emote doesnt auto-complete
4. Type out the emote on your own, in the correct Capitalization and see that the Emote is highlighted and available

**Expected behavior**
Default Twitch emotes should auto-complete like the 7TV emotes do.

**Screenshots**
![image](https://user-images.githubusercontent.com/5076085/165352656-e18427c1-9cda-4a80-a1f0-42be22febc1c.png)

My settings:
![image](https://user-images.githubusercontent.com/5076085/165352805-4db455a8-54ba-4474-ad23-1d08e8763910.png)

**Version:**
2.2.1

**Comment by AnatoleAM** [comment]
As a workaround for now you can use colon-complete (`:`)

**Comment by ahtee** [comment]
Thanks I will try that!

**Comment by AnatoleAM** [comment]
Fixed in v3.0.0 (aaaac7f)
