### ISSUE TITLE
[Feature Request] Hiding the emote menu on Twitch and YouTube should be independent of each other

### ISSUE THREAD

**Issue by robmonte** [SevenTV/Extension#261]
**Describe the bug**
If I want to hide the 7TV emote menu button on Twitch, it will also take away the button from Youtube.

**To Reproduce**
1. Go to twitch.tv
2. Click on 7TV settings
3. Check "Hide the 7TV emote menu"
4. Go to youtube.com and open a livestream
5. Observe that the emote menu button is now gone

**Expected behavior**
Changing this setting (or maybe all settings) on twitch.tv should not change settings on youtube.

**Version:**
2.2.2

**Comment by Excellify** [comment]
Wouldn't call this a bug. But having the ability to make them independent could be a nice feature.
