### ISSUE TITLE
[Request] Load 7Tv in twitch chat on other sites

### ISSUE THREAD

**Issue by dcoolArne** [SevenTV/Extension#272]
If you watch the riot twitch stream on their own site lolesports.com and have the chat open 7Tv does not load. But other plugins like bttv do load.

**To Reproduce**
1. Go to lolesports.com
2. Watch livestream and set it to twitch
3. no 7Tv

**Expected behavior**
Support Twitch chat on more sites if possible.

**Version:**
Firefox 2.2.2

**Comment by HukilauKohi** [comment]
Is this related to embedded chats?

Seems to still be an issue [here](https://github.com/SevenTV/Extension/pull/193#issuecomment-1193178036) and [here](https://github.com/SevenTV/Extension/issues/187#issuecomment-1155664052).
