### ISSUE TITLE
[Request] Option To Stop Overriding Twitch Avatar With 7TV Animated Avatar

### ISSUE THREAD

**Issue by MiaTroy** [SevenTV/Extension#281]
The animated avatar system provided allows me to change the 7TV animated avatar associated with my Twitch account, but does not allow me to remove the animated avatar entirely.
  
I have tried to set a new avatar on Twitch to stop the 7TV override, but this only works for a day or so before the Twitch avatar is overridden again. I would like to be able to disable the 7TV avatar override system.

Not sure if this is a bug or missing feature, mark appropriately :)

**Comment by AlienFreek** [comment]
I may be misunderstanding your question, but there is an option to disable animated avatars in the extension settings
and you can choose still images as your profile image on the site.

**Comment by MiaTroy** [comment]
Yes, this is the main part of the problem; I noticed the avatar system has moved to the new next.7tv.app site so it likely works slightly different now, but there is still no option to "remove 7tv avatar and use twitch avatar instead"  

The second part of my issue was that the 7tv avatar would override my Twitch avatar, even after updating my twitch avatar to a different avatar (the old 7tv avatar would keep overriding the new Twitch avatar rendering the update on Twitch's side useless)
I have waited for a week to see if I could replicate this and I could not, I assume this part was user error on my part so this issue scope should be limited to [robmonte](https://github.com/robmonte)'s summary

**Comment by MiaTroy** [comment]
Scratch that second part of my previous comment, I woke up today and saw that the 7tv avatar is overriding my twitch avatar without any intervention on my part, I will now override it on Twitch once again but it is very strange that I cannot use 7tv now without obiding by its avatar system (that I only used one time out of curiosity), in summary "There should be a "remove avatar" button on the 7TV website so a user has the option to revert back to using _only_ Twitch's avatar."

**Comment by MiaTroy** [comment]
@AnatoleAM when it this change going into effect? I am still unable to see an option to remove my pfp on the website

**Comment by AnatoleAM** [comment]
@MiaTroy, this is the wrong repository for this issue. All issues here were closed because the Extension was completely rewritten, and as such no longer relevant

**Comment by MiaTroy** [comment]
thanks @AnatoleAM , I want to open another ticket for this issue in the correct place. The issue occurs the 7TV website and in profile management, would I do this here: https://github.com/SevenTV/Website ?
