### ISSUE TITLE
entire chat red [Bug] 

### ISSUE THREAD

**Issue by jonnytest1** [SevenTV/Extension#285]
**Describe the bug**
i think you should really add a settings page - i wont use it if it marks my entire chat red

**To Reproduce**
1. Go to a twtich stream
2. get lots of chat messages
3. messages are highlighted with mention color

**Expected behavior**
let me toggle this off somewhere

**Screenshots**

**Version:**
2.2.2

**Comment by Excellify** [comment]
Agree that this should be added in a future version. In the mean time you can use the FrankerFaceZ extension with the 7TV addon if you want to avoid red highlighs on mentions.
