### ISSUE TITLE
7TV disables when getting a timeout (Twitch)

### ISSUE THREAD

**Issue by qinderium** [SevenTV/Extension#296]
![image](https://user-images.githubusercontent.com/101942890/190912916-e32514b0-8473-4bba-8d85-4368908bdcc4.png)

Always after a timeout, no matter how short or long, the 7TV logo that is supposed to be next to the cog in the image disappears and my ability to auto complete emotes and spam the same message over and over as well. I assume the timeout breaks 7TV.

**Comment by thomasasfk** [comment]
> ![image](https://user-images.githubusercontent.com/101942890/190912916-e32514b0-8473-4bba-8d85-4368908bdcc4.png)
> 
> Always after a timeout, no matter how short or long, the 7TV logo that is supposed to be next to the cog in the image disappears and my ability to auto complete emotes and spam the same message over and over as well. I assume the timeout breaks 7TV.

I've created #297 for my own use, although it does introduce a new concept so not sure how viable it is for merging.

**Comment by AnatoleAM** [comment]
Fixed in v3.0.0 (aaaac7f)
