### ISSUE TITLE
[Request] Add custom filter for console messages

### ISSUE THREAD

**Issue by NickTheWilder** [SevenTV/Extension#314]
When debugging other extensions on my browser I notice that the console is filled with information related to the SevenTV extension.
I think it would be really nice to a way to toggle these logging messages within the extension, or at least minimize the amount of messages logged in the console.

![image](https://user-images.githubusercontent.com/38483425/212794333-8d08ee87-62c7-4706-b692-904316cd6780.png)

**Version:** 2.2.3

**Comment by NickTheWilder** [comment]
![image](https://user-images.githubusercontent.com/38483425/212795633-2a4390de-64e4-43c5-bf1e-83269b764b18.png)

Something as simple as a checkbox on the front-end which controls a global variable that can be accessed throughout the code. If pointed the right direction, I could help implement this in the re-write.

**Comment by AnatoleAM** [comment]
Hi, please don't open suggestions on this repository or regarding this version of the extension as it is no longer supported and will be gone soon.

See [SevenTV/ExtensionV3](https://github.com/seventv/extensionv3) for version 3.0.0 [(Beta)](https://chrome.google.com/webstore/detail/7tv-beta/fphegifdehlodcepfkgofelcenelpedj)
