### ISSUE TITLE
[Bug] 7TV Disables BTTV Emote Modifiers from functioning.

### ISSUE THREAD

**Issue by Wulfestwulf** [SevenTV/Extension#316]
**Describe the bug**
BTTV Recently added 'emote modifiers' to their emotes, however, having 7TV enabled disables the emote modifiers from having any effect on any BTTV emotes.

**To Reproduce**
1. Have BTTV and 7TV extensions
2. Try to modify a BTTV Emote in chat Ex. "w! catJAM"
3. Notice how the emote is not wide, and "w! catJAM" is visible in chat.

**Expected behavior**
Let the Emote Modifiers actually show up in chat, even with 7TV enabled.

**Screenshots**
[With 7TV and Without](https://imgur.com/a/zHksjGi)

**Version:**
Latest

**Comment by AnatoleAM** [comment]
No plans for this at this time. The way this feature was implemented is not the way we would do it.
