### ISSUE TITLE
Alternate Player with 7TV

### ISSUE THREAD

**Issue by Kensairabbit37** [SevenTV/Extension#349]
Is it at all possible to enable the use of 7TV with Alternate Player? I greatly prefer AP over default twitch, to the point of using it despite the lack of 7TV support. Would love to get the full experience with both together. Thanks

**Comment by AnatoleAM** [comment]
Not possible, Alternate Player runs inside its own extension context. We cannot touch that page, unless the developer specifically whitelisted our extension's ID.
