### ISSUE TITLE
Only Display Onboarding on Fresh Install

### ISSUE THREAD

**Issue by professorjrod** [SevenTV/Extension#350]
I think we should only display the onboarding page only on a fresh install. This is because most browsers will automatically update extensions, so users may be focusing in the middle of something and have their flow interrupted. 

A better solution would be to just have an option to view the changelog in the extension popup. I know it's hard to showcase new features but I just think there should be a less intrusive way than opening a new tab on update :)

**Comment by AnatoleAM** [comment]
This is a unique occasion for the v3.0 update, which is one massive overhaul. Onboarding will be displayed to users who previously used v2, as well as new users. However it won't open for future 3.x.x updates.
