### ISSUE TITLE
Update to 3.0.0 on Firefox broke BTTV Chat highlighting

### ISSUE THREAD

**Issue by Nogare97** [SevenTV/Extension#352]
BTTV settings allow the marking of chat messages according to keywords (for example when your or someone elses username is mentioned).
The update to 3.0.0 disabled this functionality.
Now I get replies and mentions of my username marked, but nothing else.
It also looks different (less opaque) compared to BTTV marking.
Reinstalling 7TV version 2.2.4 fixes this issue.
Used Firefox versions were 111.0.0 and 111.0.1 for Windows 10.

**Comment by EdVraz** [comment]
You can set highlights in the 7tv settings when using v3

**Comment by AnatoleAM** [comment]
Highlights are a feature, found under 7TV Settings -> Highlights

![image](https://user-images.githubusercontent.com/9599344/227000205-eb8385bf-4ae2-4397-82c5-f916cabfcce9.png)

**Comment by Nogare97** [comment]
Is there documentation how to use those?
I tried using them right now for testing purposes and they didn't do anything.
As Pattern I used my username without (at), Label empty or some string, and changed color.

**Comment by Nogare97** [comment]
Just tested it. Usernames just dont get highlighted. Highlights seem to only work in replies and with (at)myusername. It works when using words that are not usernames.

**Comment by Nogare97** [comment]
The custom highlights. I expected, when using a username, everytime that user chats or is mentioned in any way to change that messages background color (thats what I am used to from BTTV). After testing right now, it only highlights if the pattern is part of the actual message, i.e. I write my own username in chat, if the pattern is my username. Is this intended?

**Comment by AnatoleAM** [comment]
> it only highlights if the pattern is part of the actual message, i.e. I write my own username in chat, if the pattern

Currently yes, highlights are only for message content. Username and badge highlights may be added in a future update

@tikodeur this feature is supported, however you may have to migrate your settings for it to work. Generally, the 7TV extension supports everything out of the box, so that you only need 1 extension.

The ability to change highlight opacity was added by #355 and will make it to the 3.0.1 patch
