### ISSUE TITLE
[Request] Custom "mentioned" sound option (mostly solved)

### ISSUE THREAD

**Issue by TheZett** [SevenTV/Extension#358]
The only issue I have with v3 of 7tv is that I cannot change the mention sound file anymore.
Previously I had FFZ handle that, but v3 of 7tv overrides that and instead only plays its own sound file instead (which I dont like).

It would be nice if one could specify a custom sound file for the "play sound file on mention" feature.

Edit: I've checked the source files and it appears that a single "ping.ogg" file is responsible for the sound that is played when mentioned. It would be nice if that file could be made customisable.

Edit2: Modding the extension seems to break it, that's sad. Time to downgrade until I can change the sound file natively.

**Comment by TheZett** [comment]
I tried setting up custom highlights, but the sound never plays, regardless of choosing the 'default sound' or my custom sound file (its file format is supported).

I'm using Firefox btw.

**Comment by AnatoleAM** [comment]
There was a bug where disabling the built-in mention wouldn't let custom sounds play, now fixed in #372 [3.0.1](https://github.com/SevenTV/Extension/releases/tag/v3.0.1). 

Does this resolve this issue fully?

**Comment by TheZett** [comment]
Effectively yes.

It is a work-around, but functionally it does the same as what I requested, so it can be marked as done.
