### ISSUE TITLE
Big changelog popup moment improvement

### ISSUE THREAD

**Issue by sleepkever** [SevenTV/Extension#359]
Look, I watch twitch sometimes on my company laptop, so I have 7TV installed on my company laptop. Having a random popup come out of nowhere talking about an update is annoying but I will just rage click it away. If it happens when I'm presenting or sharing my screen with collegues it gets a little bit more awkward and I would be annoyed even more.

I get the need for the popup to show everyone the awesome work you guys have been doing for 3.0.0. But next time, could you maybe delay the popup until the user opens a relevant website where 7tv is used? 
That way it happens after user interaction instead of randomly, reducing frustration, while still presenting your message to the end users.

**Comment by AnatoleAM** [comment]
This will be addressed by #357
