### ISSUE TITLE
Chat only showing 1 or 2 lines

### ISSUE THREAD

**Issue by stuart523** [SevenTV/Extension#368]
Since the recent update the chat has been only showing 1 or 2 lines at the top. Instead of filling the whole space, any new messages replace the two at the top

![Screenshot 2023-03-24 000244](https://user-images.githubusercontent.com/128759006/227390495-64506bcd-7647-48d7-9e22-3fdb3b892923.png)

**Comment by AnatoleAM** [comment]
If you're on firefox, fully restart your browser. Firefox has botched the deployment of the update for some users by caching old files from the previous version.

**Comment by stuart523** [comment]
> If you're on firefox, fully restart your browser. Firefox has botched the deployment of the update for some users by caching old files from the previous version.

I tried doing that, but it didn't work unfortunately

**Comment by AnatoleAM** [comment]
Are you in a private window by any chance? If so, this will not work, since Firefox blocks IndexedDB in private browsing.

**Comment by stuart523** [comment]
> Are you in a private window by any chance? If so, this will not work, since Firefox blocks IndexedDB in private browsing.

I just checked and you're right the problem only happens in private browsing, in non-private browsing the extension works normally. Is there any way to fix it so that it works in private mode?

**Comment by Melonify** [comment]
No, but you can allow the extension to function in Private Browsing by enabling IndexedDB support in Private Browsing mode. However please note that this may be dangerous to do, as afaik Firefox's IDB implementation may leak some site presence data to disk in Private Browsing.

You can enable the setting by going to about:config and setting `dom.indexedDB.privateBrowsing.enabled` to `true`.
