### ISSUE TITLE
Cannot see inaccessible emotes when not subscribed (Twitch)

### ISSUE THREAD

**Issue by chriswyatt** [SevenTV/Extension#375]
With the official Twitch emote picker, if I am on a channel, I can see what emotes I can unlock in the emote picker. This feature seems to be missing on 7TV and there does not seem to be a way to access the official Twitch emote picker. Are there plans to add this feature?

**Comment by AnatoleAM** [comment]
Fixed by #347 #353 releasing with patch 3.0.1.
