### ISSUE TITLE
[BUG] Can't see old threads

### ISSUE THREAD

**Issue by baxsm** [SevenTV/Extension#386]
3.0 is not allowing me to view the old thread (that people are replying to), it only shows me the Last Message (on which i clicked the thread button). Addition to that Thread / Reply is pretty weird.

Original Thread: https://imgur.com/a/kc8SYXJ
What I see: https://imgur.com/a/OBFoHax
Browser: Firefox

**Comment by AnatoleAM** [comment]
I believe that the threading logic is incorrect. I'll look to fix change it to the correct behavior for 3.0.2

**Comment by koeliga** [comment]
I have the same issue since my browser updated the extension today. Also saw someone else mentioning this in twitch chat

**Comment by AnatoleAM** [comment]
This issue is currently being addressed via #422 and will make it as part of v3.0.2
