### ISSUE TITLE
[Bug] Can't click on emotes from Twitch Channels to see which channel they belong to

### ISSUE THREAD

**Issue by selvex** [SevenTV/Extension#388]
Hi, awesome extension, but recently had to deactivate it because when enabled, I can't click on emotes to see where they are from.

That's a feature Twitch added a few months ago. You can click on any emote in chat to see which channel they belong too. Of course that only works for "Twitch" emotes and not really 7tv or whatever other extensions emotes.

I have confirmed it's only with the 7tv extension.

Using latest Windows 11 with latest chrome, with latest v2 7tv extension.

**Comment by Batyodie** [comment]
Hello. If I understood you correctly, we are talking about basic twitch emoticons like ` SUBprise `. You can press the left mouse button and a small tooltip will appear, where there will be additional information about the emoticon.

![image](https://user-images.githubusercontent.com/61266300/228566708-81219149-c864-4629-9db5-0a3a71275b56.png)

Or emoticons that belong to the streamer.

![image](https://user-images.githubusercontent.com/61266300/228567937-c8c6b24a-ab37-497f-8e7c-532f7cc6af50.png)

If we are talking about this tooltip mechanic, then yes, it is not in version 2.

![image](https://user-images.githubusercontent.com/61266300/228570406-76f329bc-9048-4a15-bb03-db09bf0e84ea.png)


 A major expansion update was released two weeks ago. Version 3, the tooltip mechanic has been slightly improved, now additional information is shown on click.

![image](https://user-images.githubusercontent.com/61266300/228569378-8ba2e717-56c8-4a53-bdd1-26e2abe1ec74.png)

![image](https://user-images.githubusercontent.com/61266300/228571407-81cc6718-15a5-485d-b2a2-d8577e84fb55.png)


Try downloading the latest version of the extension. It should solve your problem.

**Comment by MatinAniss** [comment]
This bug is not a issue in V3 of 7TV, as explained by Batyodie.
