### ISSUE TITLE
[Bug] [Youtube] Regression - Custom theater mode missing from latest version

### ISSUE THREAD

**Issue by hugeblank** [SevenTV/Extension#390]
I'm not sure if this was intentional or not, but it seems that the theater mode that 7tv added is now missing from the extension, or at least it doesn't appear in the player controls bar where it used to.

7tv extension version: 3.0.0
Browser: Firefox
Browser version: 111.0.1

**Comment by Juls-AC** [comment]
Same here since weeks ago, in my case I changed to 7TV Nightly but it's still missing.

7tv extension version: 3.0.2.4000 nightly
Browser: Edge
Browser version: 111.0.1661.62

**Comment by AnatoleAM** [comment]
Closing in favor of broader issue #671
