### ISSUE TITLE
[Twitch] Not working on VODs

### ISSUE THREAD

**Issue by GregMpour** [SevenTV/Extension#391]
Chat gets completely greyed out. Both stable and nightly on FireFox.

**Comment by FourLineCode** [comment]
certain emotes not working on vod chat, Nymn's chat on vod - emote thats not working is `forsen`

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/56719270/228037609-f400cdd6-e7f6-4f67-98c9-5e7a270f2d28.png">
