### ISSUE TITLE
'Below Input' Emote Menu refreshes menu

### ISSUE THREAD

**Issue by ezlatsen** [SevenTV/Extension#396]
I noticed this minor bug for the Emote Menu, in Appearance > Interface > Emote Menu Button Placement
When the menu is set to 'Below Input', the menu does not close when clicking the 7TV emote menu button after the menu is already open. Clicking the 7TV menu button refreshes the menu instead of closing it.
I did notice that when the settings menu is open, the emote menu does open and close normally when pressing the menu button.

When the emote menu is set to 'Regular', the menu button works as expected. This only happened when set to Below Input

**Comment by Batyodie** [comment]
@ezlatsen @Melonify Hello. Am I right in thinking this is what I'm talking about?

[screencast-www.twitch.tv-2023.04.12-21_04_53.webm](https://user-images.githubusercontent.com/61266300/231545965-fe0aaabe-213d-42e2-bd95-1f9a3c8753bf.webm)

If you select "Bellow input" in the interface settings menu. By clicking on the button again, the menu does not close.

Settings option:

![image](https://user-images.githubusercontent.com/61266300/231546231-16c4c034-35c1-498a-9f61-e529949a572f.png)

But if you click on the chat area or press the "Esc" button. The menu is closed.

If everything is correct, it seems I have a solution:

#499

**Comment by MatinAniss** [comment]
This bug is no longer a issue, I believe this was fixed in #724
