### ISSUE TITLE
Don't override settings and behavior from other plugins

### ISSUE THREAD

**Issue by Valor760** [SevenTV/Extension#399]
I have installed 3 plugins:

- BTTV
- 7TV
- FFZ

Since the last update of 7tv (3.0) my settings from FFZ are now overridden, so chat appearance and other utilities are controlled by 7tv.
For example, I used to mention someone by double clicking their nickname(not sure which plugin adds it - FFZ or BTTV). Now it doesn't work.

Please add either support of other plugins or ability to disable any settings that are applied by 7tv.

**Comment by AnatoleAM** [comment]
Do not install 3 plugins that all do roughly the same things, that'll solve your problems.

**Comment by Valor760** [comment]
@AnatoleAM I've tried disabling all other plugins, and for now 7tv has too few options to configure, that will bring back my user experience, so NO, they are not all doing the same thing, but other plugins were working perfectly with each other for years.

**Comment by AnatoleAM** [comment]
If by "working perfectly with each other", you meant "FFZ is the only extension rendering the chat", then I guess that is maybe true. However, we're looking to expand our featureset massively and create a modular, expandable modding toolkit, so that simply has to change.

**Comment by Valor760** [comment]
"FFZ is the only extension rendering the chat", however that's not true. As I said in the description of the ticket - I am lacking of 'double click' functionality. This one is brought by BTTV.

If the functionality is coming, then I'll wait, until 7tv will be fully featured as FFZ one

**Comment by Valor760** [comment]
**TEMPORARY FIX TO THIS ISSUE**
There is a solution to this problem:
Delete 7TV plugin from browser -> Go to FFZ settings (upper right corner on Twitch) -> Search for '7tv' -> Add-ons -> Enable.

Now you have 7tv emotes enabled, but chat appearance and functionality is the old one.

**Comment by AnatoleAM** [comment]
My plan was to implement quick mentions as a right-click (similar to chatterino), although I suppose double left-click could be an option too.

**Comment by AnatoleAM** [comment]
> So first of all how about you let us decide what plugins we prefer to use and how we use them

You've got control over what you install in your browser :v: that's entirely up to you.

> Just make the extension compatible with others, instead of hijacking the chat.

This is not possible and is a misconception of how extensions work. There is no such thing as compatibility between browser extensions that take effect on the same components of a website. There has never been compatibility before, even before 7TV, and there will never be. Someone has to "hijack" the chat, or nothing works.

@jstmrby

**Comment by jstmrby** [comment]
@AnatoleAM

> There has never been compatibility before, even before 7TV, and there will never be. Someone has to "hijack" the chat, or nothing works.

Weirdly enough if I have some BTTV keyword highlights and some FFZ keyword highlight for some other words, they both apply. I enable 7tv and everything's gone.

Also up until recently I was able to blacklist words using BTTV, but that's gone aswell.

**Comment by AnatoleAM** [comment]
Just because there is an illusion of compatibility due to many years of development between two extensions does not actually make them compatible. 

What's happening here is that when you have both of these extensions, one of them takes care of implementing everything the other has, which might look seamless but in reality that only came after nearly a decade of clashing.

7TV is relatively new and as such some of these power-user features are not currently available. We are constantly working on improving the Extension and the great performance and QoL improvements made generally outweigh any missing feature for most users. Feel free to suggest in the issues section what you'd like to see added next.
