### ISSUE TITLE
[Feature Request] Twitch General FFZ functionality

### ISSUE THREAD

**Issue by CrazyWolf13** [SevenTV/Extension#411]
Due to recent changes in 7TV I can see that it is completely blocking any of FFZ's chat features.

I very like the new 7TV look but here are some general things I'd love to see implemented into 7TV because I can't use them anymore with 7TV "blocking" FFZ features.

- [ ] #420
![image](https://user-images.githubusercontent.com/96661824/228305060-59a58bbb-adf9-46b6-9c91-e63805b087be.png)

- [ ] #417

- [ ] #415
![image](https://user-images.githubusercontent.com/96661824/228306152-9ce70416-05d7-4c97-8b59-07cba457ffe3.png)

- [ ] #419

- [ ] #416

- [ ] #418
![image](https://user-images.githubusercontent.com/96661824/228322252-7c1149c2-a311-4d34-80f1-9833c16f9230.png)

- [ ] #421

--> Many of those could be fixed in one task if 7TV would support FFZ interaction to chat alongside.

Thank you for creating such an awesome extension!

**Comment by AnatoleAM** [comment]
Thanks for the suggestions, could you turn these into individual requests rather than grouping them into one issue?

**Comment by Melonify** [comment]
Tracked these as separate issues
