### ISSUE TITLE
Add option for mod actions to show in chat as messages

### ISSUE THREAD

**Issue by Melonify** [SevenTV/Extension#421]
Requested by @CrazyWolf13 in #411

**Comment by CrazyWolf13** [comment]
Thank you very much @Melonify for creating those issues, I thought one would be enough because they are rather small changes.

**Comment by CrazyWolf13** [comment]
> Thank you very much @Melonify for creating those issues, I thought one would be enough because they are rather small changes.

**Comment by lukashoracek** [comment]
Timeout/ban messages are added by #504
