### ISSUE TITLE
[Bug] Subscription events render as an empty message

### ISSUE THREAD

**Issue by EpikYummeh** [SevenTV/Extension#426]
I just got the new 7TV extension update and I can no longer see subscription events in chat. They render only as a blank message. This includes gifted subscriptions as well as self-subscriptions.

I can't find a way to turn off the improved 7TV chat experience without disabling the extension entirely.

Browser:
<html>
<body>

Vivaldi | 5.6.2867.58 (Stable channel) (64-bit)
-- | --
Revision | 9df76632e9f4155daed8a9a5a4c7ed94f52d3f42
OS | Windows 10 Version 21H2 (Build 19044.2728)
JavaScript | V8 10.8.168.25
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

</body>
</html>

Other Twitch extensions installed:
* FFZ
* BetterTTV

**Comment by Melonify** [comment]
This issue should already be fixed in [nightly](https://chrome.google.com/webstore/detail/7tv-nightly/fphegifdehlodcepfkgofelcenelpedj).

**Comment by EpikYummeh** [comment]
> This issue should already be fixed in [nightly](https://chrome.google.com/webstore/detail/7tv-nightly/fphegifdehlodcepfkgofelcenelpedj).

Indeed it is! I just installed and disabled the stable release and it is working as expected. Thanks for the swift response.
