### ISSUE TITLE
[Request] Switch focus to search bar after opening emote menu

### ISSUE THREAD

**Issue by lawrencebautista** [SevenTV/Extension#436]
When you click on the emote menu button it should automatically focus the search bar so the user doesn't have to click it.

**Comment by AnatoleAM** [comment]
This is currently the case, in what way does it not work for you? Please add some info about your browser/extension version

**Comment by lawrencebautista** [comment]
Chrome windows - Version 111.0.5563.147 64-bit
7TV 3.0.2

**Comment by Batyodie** [comment]
@AnatoleAM @lawrencebautista Hi. Perhaps we are talking about losing focus in the Bellow input interface mode

[screencast-www.twitch.tv-2023.04.13-15_24_15.webm](https://user-images.githubusercontent.com/61266300/231757790-046fdd33-7fef-425c-a3f6-be79ad2b314a.webm)

If I understood everything correctly. I can do it.

**Comment by lawrencebautista** [comment]
Right, i've been using "Below Input" setting. Another bug seems to be it doesn't close when you click the button again

**Comment by Batyodie** [comment]
@lawrencebautista fix. https://github.com/SevenTV/Extension/pull/509

**Comment by MatinAniss** [comment]
This bug is no longer a issue, I believe this was fixed in #724
