### ISSUE TITLE
[Bug] Emote Detail popup rendering bug when displayed under emote

### ISSUE THREAD

**Issue by nadhifikbarw** [SevenTV/Extension#452]
Emote detail popup rendered correctly when rendered on top of an emote (when message is on lower half of chat)

![image](https://user-images.githubusercontent.com/10264286/229698260-afc18db9-a2f6-4972-a797-9dfc7ae9c7da.png)

But when rendered under an emote it suffers with layout bug (when message is on upper half of chat)

![image](https://user-images.githubusercontent.com/10264286/229698567-dd890c02-c618-420b-9294-03afa1e8f683.png)

**Comment by berghall** [comment]
I can reproduce this and if no one minds, I can take a look at it.
