### ISSUE TITLE
Option to un-hide emote modifiers

### ISSUE THREAD

**Issue by agausmann** [SevenTV/Extension#482]
Even if they are not supported, I would rather be able to see them instead of being silently hidden. At least you can understand what picture the person is trying to make. Without it, there is context missing from the message.

Blacklisting and hiding them is also not perfect. New ones have been added since the initial blacklist (for example, `!w` and `!z`), and ones that 7TV doesn't recognize will still be displayed in the chat.

**Comment by AnatoleAM** [comment]
added via #526
