### ISSUE TITLE
The chat is not fixed on the bottom when it's not paused

### ISSUE THREAD

**Issue by lumynou5** [SevenTV/Extension#512]
The chat sometimes is not fixed like the image:
![screenshot](https://user-images.githubusercontent.com/84374077/232183824-b51b34a9-a555-405a-921b-5bcd7a6e299c.png)
It seems like a bug that incorrectly scrolls the chat when a new message comes.

Update:
This also happens when closes the Chat Mode hint. The chat is scrolled to a wrong place instead of scrolling back to the original place (but it works if the chat is paused and not viewing latest messages).

7tv version: 3.0.6.1000
Browser: Firefox 112.0
OS: Windows 10 & Arch Linux

**Comment by 4n0nct** [comment]
same thing here, not something urgent, but would be nice if it could be fixed

**Comment by dpthegrey** [comment]
I noticed when tab is not focused, messages piles up as count new messages and when we click on tab and it gets active, after slight delay chat scrolls and goes to live

**Comment by lumynou5** [comment]
> I noticed when tab is not focused, messages piles up as count new messages and when we click on tab and it gets active, after slight delay chat scrolls and goes to live

Yes, but this issue happens on a focused tab.
I'm not sure whether it also happens when an inactive tab gets focused, but I think that's probable if the reason is as my guess.

**Comment by dpthegrey** [comment]
@lumynou5 
1. Have you tested on Nightly? 
2. is it possible to screen record a moving chat to see the scroll effect? 

Also, do you have any specific modification based on font size or padding or any style related modification?

I am using v3.0.6.1000 Nightly version and I can see smooth scrolling with no chatbox overlapping the chat

![image](https://user-images.githubusercontent.com/49444980/233833368-03a6124c-d7e8-4877-bde3-09956d65a364.png)

**Comment by lumynou5** [comment]
> @lumynou5
> 
>     1. Have you tested on Nightly?
> 
>     2. is it possible to screen record a moving chat to see the scroll effect?
> 
> 
> Also, do you have any specific modification based on font size or padding or any style related modification?
> 
> I am using v3.0.6.1000 Nightly version and I can see smooth scrolling with no chatbox overlapping the chat
> 
> ![image](https://user-images.githubusercontent.com/49444980/233833368-03a6124c-d7e8-4877-bde3-09956d65a364.png)

Yes, I use Nightly and didn't change the stylesheet.

**Comment by lumynou5** [comment]
I just tried to use `git bisect` but can't reproduce in Chromium...
Because it seems not happening always, I don't know if it's Firefox's problem or I was just unlucky.

**Comment by lumynou5** [comment]
https://user-images.githubusercontent.com/84374077/233841024-94241214-cbd4-4450-9bac-c78f69715a3a.mp4

about 00:04

**Comment by AnatoleAM** [comment]
I am not sure what this means. Please create a new issue with the correct format and more details if this is still a problem.
