### ISSUE TITLE
Emotes not showing up on Twitch

### ISSUE THREAD

**Issue by FoxTheHeaven** [SevenTV/Extension#515]
So when someone sends an emote on Twitch, sometimes its not there until i press "reply".

I tried:
-Reinstalling 7tv
-Using 7tv in a different browser
-Clearing cache, cookies, and other data
-Reloading Twitch
-Reinstalling browser
-Relog on Twitch and 7tv

(All of this is in Opera GX and Firefox, not in the Twitch app)

**Comment by AnatoleAM** [comment]
Not enough information here, try with a clean browser environment (no other extensions, default settings, etc). If this persists, create a new issue.
