### ISSUE TITLE
[Request] Setting to hide mod chat highlights

### ISSUE THREAD

**Issue by Niller2005** [SevenTV/Extension#518]
Would be nice to have an option to change opacity and/or hide the  `Monitored Suspicious User` highlights for mods.

How it looks now:
![image](https://user-images.githubusercontent.com/3404570/232255937-fe62610a-f6f0-4692-b4b0-bda27c0a6690.png)

**Comment by MatinAniss** [comment]
#519 PR merged, issue closed.
