### ISSUE TITLE
[REQUEST] Remove Pin button

### ISSUE THREAD

**Issue by Catta1997** [SevenTV/Extension#529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This feature does not exist in the latest nightly version

- [X] I have checked the latest nightly version

### Feature Description

As a moderator i'm asking if it's possible to completly hide the "pin" button or make a popup asking if im sure, since it is near of reply i missclick a lot of time

**Comment by AnatoleAM** [comment]
This feature has been available since version 3.0.0.

![image](https://user-images.githubusercontent.com/9599344/233800833-d78be048-e192-4f6e-9b5e-51007c7d8aec.png)
