### ISSUE TITLE
[REQUEST] Option to use multiple emote sets at the same time 

### ISSUE THREAD

**Issue by MPH2210** [SevenTV/Extension#538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This feature does not exist in the latest nightly version

- [X] I have checked the latest nightly version

### Feature Description

Since the amount of available emote slots got increased again, we are at a point where the possibility of multiple emote sets being used at the same time would get very handy, especially when users want to replace emotes for Spooktober and Christmas.

This could be done by manually setting a limit of emote slots per emote set. Then these limits could be added up to see, that the total limit has not been reached yet.

Especially when using the emote list to find a specific emote that you forgot the name of is starting to get basically impossible with up to 1000 emotes. Categorizing emotes into sets would help significantly, since users would be able to narrow down the amount of emotes to look through.

**Comment by Melonify** [comment]
This is already possible through the website. Hit "Edit" on any emote set you have access to then hit "Add Origin" you can then have that sets emotes automatically be merged and synced into the base set.

**Comment by MPH2210** [comment]
Thank you, I did not know that! But I will post another feature request expanding on this.
