### ISSUE TITLE
[BUG] Pinned messages do not show emotes

### ISSUE THREAD

**Issue by IceBotYT** [SevenTV/Extension#553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Opera

### Current Behavior

Emotes don't appear in pinned messages
![image](https://user-images.githubusercontent.com/34712694/235326167-a23af8c1-d6bf-49e0-ada3-55fcf6e989d1.png)

### Expected Behavior

The emote would appear in the pinned message

### Steps To Reproduce

1. write a message with an emote
2. pin it

**Comment by Batyodie** [comment]
@IceBotYT I don't think this can be called a bug. I looked at the code and it looks like the extension basically does not process the block with the pinned message. That is, in fact, it should be a new functionality.

**Comment by AnatoleAM** [comment]
Not a bug, please re-submit this as a feature request
