### ISSUE TITLE
[BUG] Can't use vertical scroll for Viewers/Community members list

### ISSUE THREAD

**Issue by orientalsniper** [SevenTV/Extension#554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Chrome

### Current Behavior

When you are in the viewers list, you can't scroll it, you are scrolling the chat history instead.

### Expected Behavior

One should be able to scroll the viewers list.

### Steps To Reproduce

Click viewers list and try to scroll.

**Comment by Batyodie** [comment]
@orientalsniper Hi. What audience list are you talking about? If about the one shown in my example, then the scroll works there:

[screencast-www.twitch.tv-2023.05.06-16_08_01.webm](https://user-images.githubusercontent.com/61266300/236626192-cbe66b59-88cc-4bde-b97f-e6b35071eb43.webm)

Checked in nightly version Google Chrome.

**Comment by orientalsniper** [comment]
Weird that it's not showing on your side. Scrolling with the wheelmouse is not a problem, but for streams with a large audience you want to move the scrollbar manually. When I hover the mouse over the right edge I get both scrollbars for "chat" and "viewers list".

![image](https://user-images.githubusercontent.com/6079191/236646186-b26bae20-3133-474a-b6b3-36d6bb1725d2.png)

**Comment by DanielFirpo** [comment]
Ah I see. Yea without extension enabled, Twitch hides the chat scroll when the viewer list is open. With the extension enabled, it doesn't hide the scroll so they overlap and it's really hard/impossible to use.
