### ISSUE TITLE
[REQUEST] Support for Kick.com streaming site

### ISSUE THREAD

**Issue by Willaiem** [SevenTV/Extension#568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This feature does not exist in the latest nightly version

- [X] I have checked the latest nightly version

### Feature Description

It would be awesome if the 7TV extension could support the Kick.com website. 

I saw that someone already [tried to port it](https://www.reddit.com/r/KickStreaming/comments/12oefpc/7tv_unofficial_extension/), but the official support would be great to bring the Twitch community to Kick, and it would enhance the chat experience overall,

**Comment by AnatoleAM** [comment]
Initial support added via #581. Currently only supports global emotes and a very basic form of tab-completion.

**Comment by Willaiem** [comment]
Awesome! Thank you for implementing it!

I saw an issue with the spacing of the emote - it's filling the whole grid instead of being inline.
![obraz](https://github.com/SevenTV/Extension/assets/25301582/6ae20fec-3aee-4565-9559-791396adff46)

Removing the grid properties fixes that issue.
![obraz](https://github.com/SevenTV/Extension/assets/25301582/51a04c0e-51d1-44e9-9124-fb034808c0a9)

**Comment by AnatoleAM** [comment]
Interesting, this might be browser-specific. Is this firefox?

**Comment by Willaiem** [comment]
Yep ;p
Firefox 113.0.1

**Comment by Willaiem** [comment]
The issue also exists in Chrome - quite weird.
![obraz](https://github.com/SevenTV/Extension/assets/25301582/d7202cfa-5e2b-4158-b393-e79de6b250f7)
