### ISSUE TITLE
[BUG] v3.0.7 broke follower list, hides entire "For You" sidebar contents when hovering over it

### ISSUE THREAD

**Issue by SublimeAnanas** [SevenTV/Extension#595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Firefox

### Current Behavior

https://i.imgur.com/ZkEpBo6.png

Problem ceases to exist as soon as 7tv extension is disabled. 

Tried with 7tv nightly as well as the v3.0.7 release, both exhibit the same issue, started happening today.

### Expected Behavior

For You sidepar displays followed channels

### Steps To Reproduce

Hover over the sidebar, watch its contents get hidden

**Comment by AnatoleAM** [comment]
I can't seem to replicate this. Are you sure you didn't turn on the setting that disables recommended channels?
