### ISSUE TITLE
[BUG] [Youtube] [Firefox] Functionality was not reinstated

### ISSUE THREAD

**Issue by hugeblank** [SevenTV/Extension#601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Firefox

### Current Behavior

According to [this tweet](https://twitter.com/Official_7TV/status/1658259329751842818) "functionality" was reinstated to youtube.com on FF. This isn't the case. 

### Expected Behavior

I would expect to see the 7tv emotes panel, and the custom theater mode that has been missing as reported by #390. I do not. Additionally when clicking on the 7tv badge in my browser bar I would expect to see maybe some kind of configurable settings. Instead I see:
![image](https://github.com/SevenTV/Extension/assets/16393543/0569e069-ab47-4ef7-ad1c-d61dcb8e3fb5)
On clicking the big button, the page refreshes, but nothing changes. When clicking the badge icon again the same big button shows up. I have tried this with and without ad-block, and with the subset of extensions that affect youtube.com disabled.

### Steps To Reproduce

1. Allow extension to access youtube when onboarding
2. Go to a YT livestream.
3. Nothing 7tv provided pre-3.0 is present.
4. Click on badge icon in browser bar
5. Click big "Enable" button, refreshing the page
6. Repeat from step 4 to your hearts content

**Comment by AnatoleAM** [comment]
Functionality reinstated refers to basic YouTube support being re-added after it had been fully disabled in a previous version. It does mean that theater mode or the emote menu has been re-implemented.
