### ISSUE TITLE
[REQUEST] Live chat translations

### ISSUE THREAD

**Issue by XHawk87** [SevenTV/Extension#618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This feature does not exist in the latest nightly version

- [X] I have checked the latest nightly version

### Feature Description

I came across this extension that provides a live translations panel in twitch chat: https://github.com/LiveTL/LiveTL

Unfortunately, it's not compatible with 7TV, and they're not likely to be able to provide compatibilty in the near future: https://github.com/LiveTL/LiveTL/issues/444

It would be really useful for chatters, mods and streamers to have immediate access to translations. Is it possible to make this compatible with LiveTL or otherwise integrate this feature into 7TV?

**Comment by Batyodie** [comment]
Correct me if I'm wrong. From what I understand, the extension does not provide automatic translation through some kind of service, like google-translate.

Instead, it provides a "live translation", by live it means that a person who speaks the language can add his own translation and other people will see it during the broadcast. That's how I understood this concept.

With automatic translation as a function, everything seems to be clear. There is some kind of library that will do the translation, then you need to solve the issue of integrating such a library into the extension and adding translation functionality.

But if you do it according to the same principle as in the example of the extension, without using automatic translation, it will be an order of magnitude more difficult and it is not clear how much it is really needed.

**Comment by Batyodie** [comment]
If you do it through automatic translation, then it does not seem to be a very difficult task. You just need to understand which library to use for translation.

@AnatoleAM What do you think about it?

**Comment by DanielFirpo** [comment]
I don't think it's that simple. I don't think there's any libraries that can be shipped with the extension and do translation locally. I think this is something that's only done through an api, which can be expensive. It would be cool, Facebook gaming has a way to translate chats and it works really well, but I don't think it's practical/7TV would ever want to spend that amount of money for a small feature.

**Comment by XHawk87** [comment]
For automatic translations, this looks like an interesting option: https://github.com/LibreTranslate/LibreTranslate

**Comment by Batyodie** [comment]
@DanielFirpo 
I wasn't thinking about translating the entire chat at once. And about the point translation of the message, at the request of the user.

Conditionally, by clicking on the text of the message, there will be some kind of button that can optionally translate the message, ignoring emoticons.

After clicking, the message tokens are sent to some helper function from the translation library, like this [translate](https://www.npmjs.com/package/translate)

As a result, we have a reactive toggle switch, to translate and back from the selected message.

**Comment by DanielFirpo** [comment]
Yea that's what I had in mind too, a button that translates a single message. Never thought you meant whole chat. Also you linked a package that just wraps various translation APIs, so you didn't really address my concern about the feature costing money.

What @XHawk87 linked though is interesting. I'm sure it's not as good as the big APIs but it's free, so that's a possibility for sure.

**Comment by XHawk87** [comment]
I notice the translation package that @Batyodie linked also supports LibreTranslate. That offers a lot of flexibility. That could be a free option, and if a user wanted a premium option, they could supply their own API key for whichever engine they want.

**Comment by DanielFirpo** [comment]
LibreTranslate [isn't actually free](https://portal.libretranslate.com/) if you're not hosting it yourself. So the translate package could be used but it won't save from creating a server for LibreTranslate/adding it to the existing 7TV API.
