### ISSUE TITLE
[BUG] Can't Link YouTube Account With 7TV

### ISSUE THREAD

**Issue by natto62** [SevenTV/Extension#662]
**How to reproduce issue:**
1. Go to https://7tv.app/users/YOUR_USERID and click the YouTube button under Link Accounts:
![image](https://github.com/SevenTV/Extension/assets/26265030/f6c3b6d6-242c-4b2d-804e-127d504852c0)

2. This then takes you to https://old.7tv.app/link-youtube, where you get prompted to sign in with Twitch: 
![image](https://github.com/SevenTV/Extension/assets/26265030/d80a8100-3f75-4add-9ce5-0bf1e62da882)

3. The following error is then displayed in a new window that opens, you are unable to continue further: "{"status_code":404,"status":"Not Found","error":"Unknown Route","error_code":70498,"details":{"message":"The API endpoint requested does not exist"}}"
![image](https://github.com/SevenTV/Extension/assets/26265030/912cdaea-58a8-40ea-bade-3dcc191af52f)

**Browsers I've Tested:**
- Chrome
- Edge
- Firefox

There's currently no open issue for this problem. Is it to be resolved, or is YouTube account linking to be removed entirely?

**Comment by peep0777** [comment]
the youtube login has been broken forever and won’t be fixed at all

**Comment by AnatoleAM** [comment]
Issue unrelated to extension

**Comment by natto62** [comment]
> Issue unrelated to extension

Since it's unrelated to the extension, is there a seperate GitHub project for 7TV (not the extension) where I can create an issue? Would be good to get a bit more out of this than basically just "not my problem".

**Comment by gluax** [comment]
Any update on a relevant link for this? I can't find any way to connect 7tv to a YouTube channel to add 7tv emotes there.
