### ISSUE TITLE
[BUG] Kick Auth Flow Removes Social Links

### ISSUE THREAD

**Issue by notpallav** [SevenTV/Extension#677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Chrome

### Current Behavior

Current Kick Auth Flow involves updating Kick bio using the /update_profile api endpoint.
This endpoint is also used to update Social Media links.
However, since the auth flow only sends the bio, and omits the twitter/instagram/youtube/etc fields, it causes the social media links to reset.

before:
![image](https://github.com/SevenTV/Extension/assets/43105309/ebbccf21-3d32-4e87-9be8-a2d6688f069b)
![image](https://github.com/SevenTV/Extension/assets/43105309/821458a3-2649-4830-8776-4f1633a80269)

### Expected Behavior

In calls to /update_profile, pass the existing social media fields as well, so social media links are not affected.
discord, facebook, instagram, tiktok, twitter, youtube

### Steps To Reproduce

1. Set social media usernames at https://kick.com/dashboard/settings/profile (scroll down to Social Media)
2. Sign in to 7tv using the Connect 7tv button
3. Observe that social media usernames are now blank, and social media links have disappeared from your channel page.

**Comment by AnatoleAM** [comment]
Good shout, thanks :slightly_smiling_face:
