### ISSUE TITLE
[BUG] Can not open Emote Menu on Twitch

### ISSUE THREAD

**Issue by HeroAAX** [SevenTV/Extension#749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Firefox

### Current Behavior

When clicking the emote menu on Twitch (right next to the Textfield) nothing happens. 

### Console Output:
```
TypeError: o.closePaidPinnedChatCardForEmotePicker is not a function
    f moz-extension://4025602c-e01b-4b44-848a-d91ef3010207/assets/seventv.EmoteMenuModule.3.0.0.js:1
    vm moz-extension://4025602c-e01b-4b44-848a-d91ef3010207/assets/seventv.TooltipDirective.3.0.0.js:1
    jt moz-extension://4025602c-e01b-4b44-848a-d91ef3010207/assets/seventv.TooltipDirective.3.0.0.js:1
    We moz-extension://4025602c-e01b-4b44-848a-d91ef3010207/assets/seventv.TooltipDirective.3.0.0.js:1
    n moz-extension://4025602c-e01b-4b44-848a-d91ef3010207/assets/seventv.TooltipDirective.3.0.0.js:1
[seventv.TooltipDirective.3.0.0.js:1:14301](moz-extension://4025602c-e01b-4b44-848a-d91ef3010207/assets/seventv.TooltipDirective.3.0.0.js)
    ff moz-extension://4025602c-e01b-4b44-848a-d91ef3010207/assets/seventv.TooltipDirective.3.0.0.js:1
    Vn moz-extension://4025602c-e01b-4b44-848a-d91ef3010207/assets/seventv.TooltipDirective.3.0.0.js:1
    jt moz-extension://4025602c-e01b-4b44-848a-d91ef3010207/assets/seventv.TooltipDirective.3.0.0.js:1
    We moz-extension://4025602c-e01b-4b44-848a-d91ef3010207/assets/seventv.TooltipDirective.3.0.0.js:1
    n moz-extension://4025602c-e01b-4b44-848a-d91ef3010207/assets/seventv.TooltipDirective.3.0.0.js:1
```
    

### Expected Behavior

Menu opens and the user is able to post Emotes.

### Steps To Reproduce

1. Start Mozilla Firefox (V 114.0.2) 64 Bit
2. open Twitch and Join a Stream
3. click on Emote Menu

**Comment by AnatoleAM** [comment]
Please update or re-install the extension, you are 14 versions behind the latest. (Version 3.0.0 when current version is 3.0.14)

**Comment by HeroAAX** [comment]
Thank you,
I accidently ran the stable version though it works with nightly
