### ISSUE TITLE
[BUG] Not working on youtube

### ISSUE THREAD

**Issue by xznhj8129** [SevenTV/Extension#756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Chrome

### Current Behavior

For a few weeks, the extension has been completely broken on youtube. I don't use twitch, i dont know if it works there. But on Brave browser the extension itself will not display any emotes or functions, the extension icon will just display "onboarding coming soon". Trying on firefox, both stable and nightly will show "enable for youtube", and on clicking it the page will reload, but nothing has changed and again the icon asks to "enable for youtube", clicking it will just reload the page. Extension completely broken.
Brave Extensions:
Ublock Origin
Consent-O-Matic
YouTube Livestreams Theater Mode
Return YouTube Dislike
Tampermonkey
7TV Nightly
AutoplayStopper
SponsorBlock for YouTube - Skip Sponsorships
Stream Cleaner
Wayback Machine
Cookie AutoDelete
Old Twitter Layout (2023)

Firefox extensions: 
Ublock Origin
Cookie AutoDelete
YouTube Livestreams Theater Mode

### Expected Behavior

Any kind of sign it's loaded

### Steps To Reproduce

Try to use plugin on youtube

**Comment by AnatoleAM** [comment]
Currently only chat emotes are supported on youtube as legacy support.
