### ISSUE TITLE
not log in when click log in intro 7tv button[BUG] <title>

### ISSUE THREAD

**Issue by Matiz753** [SevenTV/Extension#766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Opera

### Current Behavior

try log in using big 7tv button on kick and nothing the webside open new window, log in and nothing get back to this button and click again log in, aslo cannot use kick chat

### Expected Behavior

try log in using big 7tv button on kick and nothing the webside open new window, log in and nothing get back to this button and click again log in, aslo cannot use kick chat

### Steps To Reproduce

try log in using big 7tv button on kick and nothing the webside open new window, log in and nothing get back to this button and click again log in, aslo cannot use kick chat

**Comment by AnatoleAM** [comment]
You've repeated the same thing 3 times in the wrong boxes. Please make an effort
