### ISSUE TITLE
[BUG] Emotes don't appear when using 7TV or 7TV Nightly

### ISSUE THREAD

**Issue by Skubers** [SevenTV/Extension#778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Other

### Current Behavior

I'm using AtlasOS (22H2 Win10) and Brave Browser. Issue started appearing after I changed my PC. Whenever I restart my PC, and start the browser, I see the 7TV Onboarding page (seems like it doesn't remember that I've already had OOBE). Additionally, I can't see any 7TV emotes on any streams.

I don't have any other Twitch.tv extensions

### Expected Behavior

I can see the emotes and I don't get the Onboarding page every restart

### Steps To Reproduce

Have AtlasOS (22H2 Win10)
Install Brave
Install the extension
Observe the issue

**Comment by AnatoleAM** [comment]
If you're getting the onboarding page on every restart, you most likely have some sort of amnesia settings that automatically clears all data, which would also explain why emotes don't show as persistent storage is required.

Please check your browser settings.
