### ISSUE TITLE
Threads spawn from wrong message after twitch update

### ISSUE THREAD

**Issue by EdVraz** [SevenTV/Extension#831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Chrome, Firefox

### Current Behavior

Replying to a message from a thread creates a new thread. Probably related to the latest twitch update https://dev.twitch.tv/docs/change-log/

### Expected Behavior

The message to be put into the original thread 

### Steps To Reproduce

Create a message
Reply to the message with a different user
Reply to the message of the other user
A new thread should be created that does not contain the original message.

**Comment by razorlikes** [comment]
Same issue here on Chrome. Replying to a thread will always send a reply to the first message in the thread and thus create a new thread. Super annoying...

**Comment by AnatoleAM** [comment]
This is the normal behavior, twitch "threads" are mostly a client side concept, where after one reply to a message, all further replies downstream are considered to be part of the initial message that was replied to.

**Comment by razorlikes** [comment]
> This is the normal behavior 

No it's not. Nevertheless it seems to finally be fixed as of this commit: https://github.com/SevenTV/Extension/commit/da05ccc54edc67809a96d0837de9d85164d0f694
