### ISSUE TITLE
[BUG] <Emotes disapearing>

### ISSUE THREAD

**Issue by DtZNimpo** [SevenTV/Extension#835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Chrome

### Current Behavior

On Twitch: Some channel will have extra 7tv on their channel and they will randomly disapear only showing the default 7tv emotes "PETPET , BillyApproves, FeelsWeirdMan, etc" (they even disapear from the viewable list of emotes to manually select, only showing the default one)

### Expected Behavior

On Twitch: Channels that have added customed emotes should always been available and displayed, when pressing TAB to autocomplete them they should show up.  And all the emotes used by the channel should be displayed at all time regardless.

### Steps To Reproduce

Go to a twitch channel that have customed 7tv on top of the default one, go to another tab on Chrome for a few minutes , come back to the twitch channel you were watching and the customed emotes added by the channel will be removed from the emotes u can pick and they will no longer work with autocompletion (TAB) except for the 7tv Default one.

**Comment by AnatoleAM** [comment]
Should be fixed as of #941
