### ISSUE TITLE
[BUG] Colon Completion Extension Fails to Locate 'lookUp' Emote with Substring Search

### ISSUE THREAD

**Issue by Davidn0** [SevenTV/Extension#870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Firefox

### Current Behavior

When attempting to use Colon Completion to search for a specific name, such as ':up' the extension encounters difficulties when the name contains the desired substring. This issue has been observed specifically with the 'lookUp' emote created by JasonIGuess. The extension successfully identifies the emote when searching for 'look' or 'kup' but fails to do so when typing ':up' or ':Up'

### Expected Behavior

When searching for a name using Colon Completion, the extension should accurately locate names containing the desired substring, regardless of whether the substring includes uppercase letters. In the case of the 'lookUp' emote, created by JasonIGuess, the extension should successfully identify it when searching for 'up', 'Up' or any variation that includes the desired substring.

### Steps To Reproduce

Start a search by typing a colon (':') followed by the substring 'up'
Observe that the extension fails to locate the 'lookUp' emote created by JasonIGuess.

**Comment by AnatoleAM** [comment]
Couldn't reproduce.
