### ISSUE TITLE
[BUG] Stuck in onboarding

### ISSUE THREAD

**Issue by thulle** [SevenTV/Extension#930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Firefox

### Current Behavior

Setting up a separate firefox profile for twitch I got stuck in the onboarding process after installing the 7tv addon.
After completing it, nothing changes in the 7tv addon dropdown. Behaves exactly as in #495.
Tried disabling all other addons to rule out weird interactions. 
Firefox 119.0 (64-bit) on linux.

### Expected Behavior

"Onboarding =>" disappears after completing the onboarding.

### Steps To Reproduce

Created a new firefox profile, installed the standard internet condoms, uBlock origin, uMatrix, DDG Privacy Essentials. 

Logged into twitch, realized emotes are gone.  

Surf to 7tv.app

click stable release

get a notification that sas "7tv.app - The addon could not be downloaded because of a connection failure."

press F12

check network debugger

click stable relase button again

get NS_BINDING_ABORTED-error, probably since it's trying to do a cross-domain addon installation where download is from 
https://extension.7tv.gg/v3.0.9/ext.xpi and not 7tv.app

open xpi-url in new tab

install extension

realize onboarding process never completes

install nightly build since that's a requirement for filing a bug

disable stable build, and all other plugins to rule out interactions

restart firefox

try to complete onboarding process again

realize it still doesn't work

**Comment by AnatoleAM** [comment]
This is usually caused if you have some specific settings turned on that disable the extension's ability to store data, like blocking cookies or site storage.
