### ISSUE TITLE
[REQUEST] Get the firefox extension signed and uploaded

### ISSUE THREAD

**Issue by Headedbranch225** [SevenTV/Extension#934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This feature does not exist in the latest nightly version

- [X] I have checked the latest nightly version

### Feature Description

The versions aren't signed so firefox prevents installing them without them being temporary in debug mode, can we get the latest version signed with firefox so it doesn't install it and shows a popup and refers to [this site](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct) where it mentions extensions have to be signed for them to be accepted [imgur because github doesnt want to let me upload](https://imgur.com/a/TecknFV)

**Comment by AnatoleAM** [comment]
The signed version is uploaded on [7tv.app](https://7tv.app)
