### ISSUE TITLE
[BUG] 7TV app not playing ping sound.

### ISSUE THREAD

**Issue by NoobKeksTV** [SevenTV/Extension#969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [x] I am using the latest nightly version

### What browsers are you seeing the problem on?

Chrome

### Current Behavior

I get pinged in chat. Message gets  marked properly and my name is in color, but the ping sounds doesnt play no matter if tab is open or not

### Expected Behavior

To receive a ping sound whenever i get pinged in chat

### Steps To Reproduce

Install the Addon, Set it up, Get Pinged (lol)

**Comment by AnatoleAM** [comment]
Can you show a screenshot of the highlights tab in settings?

**Comment by NoobKeksTV** [comment]
eh where would i find this setting menu?  only thing i can find is the onboarding rn.

if i click the extension icon this is what i get 
![nLD7](https://github.com/SevenTV/Extension/assets/30929430/72234f6d-b6a1-4af4-af97-1b8e93b4e931)

**Comment by AnatoleAM** [comment]
It's on twitch. Top-right or the cog in the emote menu

**Comment by NoobKeksTV** [comment]
oh wow. thanks
ye i alredy saw that the ping stuff is turned off for whatever reason.
in the onboarding i enabled it all and there it didnt get saved.... will try again now..

**Comment by NoobKeksTV** [comment]
ffs it works. well i guess thank you. 
idk why it didnt save but activating it manually fixxed it all. thank yu
