### ISSUE TITLE
[BUG] Who uses what emote channels not working 

### ISSUE THREAD

**Issue by Daxy7** [SevenTV/Extension#982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Firefox

### Current Behavior

Something that used to show up a couple months ago on 7TV website
Also reported here https://github.com/SevenTV/WebsiteNext/issues/6

### Expected Behavior

⠀

### Steps To Reproduce

https://7tv.app/emotes/60ae8d9ff39a7552b658b60d

[Image of no channels](https://github.com/SevenTV/Extension/assets/91396482/ab7cb3b6-19cb-444a-9014-87b20be027e7)
placeholder shows up though: [Screenshot](https://github.com/SevenTV/Extension/assets/91396482/e363106d-0c90-42e9-b66e-9bf40c9afb75)

**Comment by MatinAniss** [comment]
Wrong place for this issue, issues here are for the web extension only. This was done intentionally and is temporary.
