### ISSUE TITLE
[REQUEST] 7tvv is not working

### ISSUE THREAD

**Issue by xEalexplay** [SevenTV/Extension#996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This feature does not exist in the latest nightly version

- [X] I have checked the latest nightly version

### Feature Description

greetings, i have problems with connecting my twitch account with 7tv. It just suddenly disconnect and i cannot see the emotes . I tried to reconnect but once i just log in, it just close again without success. i verify if it is massive, but it is just me having this problem.

![Capture 1](https://github.com/SevenTV/Extension/assets/158594693/50ef4789-1954-41ae-9a00-99c41ad43ece)

**Comment by TroyKomodo** [comment]
I think this was related to the twitch react 18 experiment, feel free to open if it still happens
