### ISSUE TITLE
Clicking on 7tv logo does this

### ISSUE THREAD

**Issue by 4Sol** [SevenTV/Extension#999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Chrome

### Current Behavior

https://i.imgur.com/LsHNA0r.png

### Expected Behavior

-

### Steps To Reproduce

-

**Comment by ap3x01** [comment]
also experiencing this. Can't use the extension at kick.com bc of this.

**Comment by TroyKomodo** [comment]
This is a known issue, and we have fixed it but the extension has not been updated on the store.
